image: Visual Studio 2019

platform:
  - x64
  - x86

configuration:
  - Release
  - Debug

environment:
  MSVC_VERSION: 16
  PYTHON: "C:\\Python37-x64"

install:
  # Fetch and setup conan
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe --quiet install conan
  - conan remote add barco %CONAN_URL%
  - conan user -p %CONAN_API_KEY% -r barco %CONAN_USER%
  
  # Install Ninja
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\deps\ninja > nul
  - del ninja.zip
  - set PATH=C:\projects\deps\ninja;%PATH%
  
  # Select MSVC version
  - if "%platform%" == "x64" (
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
    )
  - if "%platform%" == "x86" (
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
    )
    
  # Conan settings
  - conan profile new default --detect
  - conan profile update settings.compiler="Visual Studio" default
  - conan profile update settings.compiler.version=%MSVC_VERSION% default
  - conan profile update settings.arch=x86 default
  - conan profile update settings.build_type=%configuration% default
  - if "%platform%" == "x64" ( conan profile update settings.arch=x86_64 default )
    
before_build:
  - cd /D %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake -G "CodeBlocks - Ninja" -DCMAKE_BUILD_TYPE=%configuration% ..\cmake

build_script:
  - cmake --build . --target all --config %configuration%

test_script:
   - cmake --build . --target test
  
after_test:
  - cd /D %APPVEYOR_BUILD_FOLDER%
  - conan.build.cmd
